apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feast-benchmark

resources:
  - namespace.yaml
  - results-pvc.yaml

configMapGenerator:
  # Benchmark configuration from .env file
  - name: benchmark-config
    envs:
      - benchmark.env
    options:
      disableNameSuffixHash: true
  
  # Benchmark script from Python file
  - name: benchmark-script
    files:
      - benchmark_runner.py
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: feast-benchmark
      app.kubernetes.io/part-of: feast
