apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-results
  labels:
    app.kubernetes.io/name: feast-benchmark
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
