apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: feast-ray
  namespace: __NAMESPACE__
  labels:
    app: feast-ray
spec:
  rayVersion: "2.35.0"
  headGroupSpec:
    enableIngress: false
    rayStartParams:
      block: "true"
      dashboard-host: "0.0.0.0"
      num-gpus: "0"
    serviceType: ClusterIP
    template:
      metadata:
        labels:
          app: feast-ray
          ray.io/group: headgroup
      spec:
        containers:
          - name: ray-head
            image: "quay.io/modh/ray:2.35.0-py311-cu121"
            imagePullPolicy: IfNotPresent
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh", "-c", "ray stop"]
            ports:
              - containerPort: 6379
                name: gcs
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
            resources:
              requests:
                cpu: "1"
                memory: 4Gi
              limits:
                cpu: "2"
                memory: 8Gi
  workerGroupSpecs:
    - groupName: feast-workers
      replicas: 2
      minReplicas: 1
      maxReplicas: 4
      rayStartParams:
        block: "true"
        num-gpus: "0"
      template:
        metadata:
          labels:
            app: feast-ray
            ray.io/group: workergroup
        spec:
          containers:
            - name: ray-worker
              image: "quay.io/modh/ray:2.35.0-py311-cu121"
              imagePullPolicy: IfNotPresent
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh", "-c", "ray stop"]
              resources:
                requests:
                  cpu: "1"
                  memory: 4Gi
                limits:
                  cpu: "2"
                  memory: 8Gi
