apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
  namespace: __NAMESPACE__
stringData:
  redis: |
    connection_string: redis.__NAMESPACE__.svc.cluster.local:6379
  sql: |
    path: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres.__NAMESPACE__.svc.cluster.local:5432/${POSTGRES_DB}
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: credit-scoring
  namespace: __NAMESPACE__
  labels:
    feature-store-ui: enabled
spec:
  feastProject: credit_scoring_local
  feastProjectDir:
    git:
      url: https://github.com/accorvin/feast-credit-score-local-tutorial.git
      ref: demo
  services:
    offlineStore:
      persistence:
        file:
          type: duckdb
    onlineStore:
      persistence:
        store:
          type: redis
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
        - secretRef:
            name: postgres-secret
        env:
        - name: MPLCONFIGDIR
          value: /tmp
        resources:
          requests:
            cpu: 150m
            memory: 128Mi
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
        server:
          envFrom:
          - secretRef:
              name: postgres-secret
          env:
          - name: MPLCONFIGDIR
            value: /tmp
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
          restAPI: true
