apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feast-benchmark

resources:
  - ../base
  - redis.yaml
  - postgres.yaml

secretGenerator:
  - name: postgres-secret
    literals:
      - POSTGRES_USER=feast
      - POSTGRES_PASSWORD=feast
      - POSTGRES_DB=feast
    options:
      disableNameSuffixHash: true
