apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-ray-batch-engine
  namespace: __NAMESPACE__
data:
  config: |
    type: ray.engine
    use_kuberay: true
    kuberay_conf:
      cluster_name: feast-ray
      namespace: __NAMESPACE__
      runtime_env:
        pip:
          - datasets
          - sentence-transformers
        working_dir: __FEATURE_REPO_DIR__
    max_workers: 4
    enable_optimization: true
    broadcast_join_threshold_mb: 100
    target_partition_size_mb: 64
    window_size_for_joins: 1H
